export const Categories = [
    {
        id: 1,
        label: 'Food and Drink',
        category: 'Restaurant',
        icon: 'restaurant',
        image: '/images/foodanddrink.png',
    },
    {
        id: 2,
        label: 'Cafe',
        category: 'cafe',
        icon: 'nightlife',
        image: '/images/Cafe.png',
    },
    {
        id: 3,
        label: 'Tours & Attractions',
        category: 'Attractions',
        icon: 'surfing',
        image: '/images/attractions.png',
    },
    {
        id: 4,
        label: 'Bar & Nightlife',
        category: 'Bar & Nightlife',
        icon: 'home_repair_service',
        image: '/images/nightLife.png',
    },{
        id: 5,
        label: 'Hotel & Lodging',
        category: 'Hotel & Lodging',
        icon: 'home_repair_service',
        image: '/images/hotel.png',
    },{
        id: 6,
        label: 'Retail & Shopping',
        category: 'Retail & Shopping',
        icon: 'home_repair_service',
        image: '/images/shopping.png',
    },{
        id: 7,
        label: 'Beauty & Spa',
        category: 'Beauty & Spa',
        icon: 'home_repair_service',
        image: '/images/beauty_and_spa.png',
    },{
        id: 8,
        label: 'Health & Wellness',
        category: 'Health & Wellness',
        icon: 'home_repair_service',
        image: '/images/gym.jpg',
    },{
        id: 9,
        label: 'Automotive',
        category: 'Automotive',
        icon: 'home_repair_service',
        image: '/images/automotive.png',
    },{
        id: 10,
        label: 'Professional Services',
        category: 'Professional Services',
        icon: 'home_repair_service',
        image: '/images/professional_services.png',
    },{
        id: 11,
        label: 'Real Estate',
        category: 'Real Estate',
        icon: 'home_repair_service',
        image: '/images/real_estate.png',
    },{
        id: 12,
        label: 'Other',
        category: 'Other',
        icon: 'home_repair_service',
        image: '/images/other.png',
    },
]