export const FILTER_BUSINESSES = [
    {
        id: 0,
        name: 'Roots',
        slug: 'roots',
        description: '',
        about: '',
        category: 'Restaurant',
        parish: 'St. Ann',
        city: 'Ocho Rios',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 1,
        reviewCount: 200,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: false,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 1,
        name: 'Safari',
        slug: 'safari',
        description: '',
        about: '',
        category: 'Attraction',
        parish: 'Trelawny',
        city: 'Falmouth',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 2.9,
        reviewCount: 170,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: false,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 2,
        name: 'Blue Nose',
        slug: 'blue_nose',
        description: 'Seafood restaurant. Get the best seafood in town.',
        about: '',
        category: 'Restaurant',
        parish: 'St. Mary',
        city: 'Richmond',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 3.0,
        reviewCount: 46,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: false,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 3,
        name: 'Blue Hole',
        slug: 'blue_hole',
        description: '',
        about: '',
        category: 'Attraction',
        parish: 'St. James',
        city: 'Montego Bay',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 2.5,
        reviewCount: 550,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: false,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 4,
        name: 'Kimz Seafood',
        slug: 'kimz_seafood',
        description: 'The definitive Kingston seafood experience. Authentic flavors meets breathtaking harbor views.',
        about: `Experience the authentic flavors of Jamaica at Blue Lagoon Cove. Nestled on the pristine sands of Port Antonio,
            our restaurant offers a farm-to-table menu featuring fresh local seafood, jerk specialties, and hand-crafted tropical cocktails.`,
        category: 'Restaurant',
        parish: 'Manchester',
        city: 'Mandeville',
        address: '',
        image: '/images/villas.png',
        gallery: ['/images/attractions.png', '/images/villas.png', '/images/restaurant.png', '/images/services.png'],
        rating: 5.0,
        reviewCount: 128,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: false,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 5,
        name: 'Kanopi House',
        slug: 'kanopi_house',
        description: '',
        about: '',
        category: 'Wellness',
        parish: 'Westmoreland',
        city: 'Negril',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 4.9,
        reviewCount: 145,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: true,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 6,
        name: 'Panopi House',
        slug: 'panopi_house',
        description: '',
        about: '',
        category: 'Wellness',
        parish: 'Westmoreland',
        city: 'Negril',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 4.9,
        reviewCount: 145,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: true,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
    {
        id: 7,
        name: 'Manopi House',
        slug: 'manopi_house',
        description: '',
        about: '',
        category: 'Wellness',
        parish: 'Westmoreland',
        city: 'Negril',
        address: '',
        image: '/images/villas.png',
        gallery: [],
        rating: 4.9,
        reviewCount: 145,
        priceRange: '',
        averagePrice: '',
        trending: false,
        featured: true,
        verified: false,
        tags: '',
        phone: '',
        email: '',
        website: '',
        instagram: '',
        facebook: '',
        hours: '',
        views: '',
        favorites: '',
        latitude: '',
        longitude: '',
        createdAt: '',
        updatedAt: ''
    },
]